### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by gopalchobey9** [31b4/Leetcode-Premium-Bypass#100]
**Describe the bug**
the scroll bar scroll to infinity

**Screenshots**
![Screenshot 2024-02-06 082813](https://github.com/31b4/Leetcode-Premium-Bypass/assets/100458189/70189eb5-776a-4597-bb37-a889d9a860f6)

**Desktop (please complete the following information):**
 - Browser chrome
 -window 11

**Additional context**

**Comment by RikiRk** [comment]
Yess It's permanently disabled

**Comment by gopalchobey9** [comment]
ok

**Comment by UsmanMERN** [comment]
its not uploading into my browser i am trying 
![Capture](https://github.com/31b4/Leetcode-Premium-Bypass/assets/110949253/b9735f32-e1f1-4784-9848-ce9153728657)

**Comment by 31b4** [comment]
sorry guys, i had to, check #99

**Comment by 31b4** [comment]
@gopalchobey9 Check #99 ITS WAS DISABLED
