### ISSUE TITLE
Unable to check how many companies asked this question.

### ISSUE THREAD

**Issue by 9582anupam** [31b4/Leetcode-Premium-Bypass#11]
After opening a problem description, Which I click on companies to check which companies asked for this question. It shows to the option to buy subscription.

**Comment by 31b4** [comment]
Did it turn to green? Which problem? Can you provide with more specific information about the issue?

**Comment by 31b4** [comment]
@9582anupam

**Comment by 9582anupam** [comment]
All other features are working fine. On refreshing the problems page I can see frequency of questions. I am able to see questions from selected companies and premium questions too. But the problem is when I select any problem and then click on "companies" to check which companies asked this question, It shows buy subscription pop up. This same happens in all the problems, for example LEETCODE1 TWOSUM.

**Comment by 31b4** [comment]
did you try to refresh the page at the problem page? It's working for me on every problem. @9582anupam

**Comment by 31b4** [comment]
@rahul4tripathi2 Its currently not working for dynamic ui. Only for split ui, but we are working on fixing it. I will let you know when its working.

**Comment by 31b4** [comment]
@9582anupam Companies tag button was fixed for dynamic ui, we are still working on editorial https://github.com/31b4/Leetcode-Premium-Bypass/releases/tag/1.1.1

**Comment by 9582anupam** [comment]
@31b4 Thanks, Companies tag button is Working fine now.
