### ISSUE TITLE
Question does not appear when on click on company tag

### ISSUE THREAD

**Issue by JasrajChouhan** [31b4/Leetcode-Premium-Bypass#110]
Hey,
When we click on a company tag, it does not open the question page, and the circle moves continuously.
![Screenshot 2024-02-12 195539](https://github.com/31b4/Leetcode-Premium-Bypass/assets/106804923/cc398c20-6eed-49c7-93a9-e8dfb8cf9564)

**Comment by 31b4** [comment]
#99
