### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shiva989-f** [31b4/Leetcode-Premium-Bypass#112]

**Comment by praveen027** [comment]
It's disabled due to dmca guidlines #99, clearly mentioned in the readme !! Why is it so difficult for you to see?

**Comment by praveen027** [comment]
Here, take 👓 from me.

**Comment by shiva989-f** [comment]
Understood
thank you

**Comment by 31b4** [comment]
> It's disabled due to dmca guidlines #99, clearly mentioned in the readme !! Why is it so difficult for you to see?

yeah i still got these issues daily, idk where else should i mention that its disabled😅

but its fine

**Comment by 31b4** [comment]
and btw @shiva989-f if you are making an issue, do NOT make it like this:
<img width="560" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/0581a046-ac76-4bbd-960a-99a3f53e1717">
i've got alot of these issues when i was working on this extension and i cant do anything with it, submitting issues were made for you to lmk the issue and describe it how, when, (why) it happens, so dont do issues like this to other repos pls, 'not working x,y' we cant do anything with that...
