### ISSUE TITLE
How can i get the Leetcode API access?

### ISSUE THREAD

**Issue by AkashKumarSingh11032001** [31b4/Leetcode-Premium-Bypass#117]
Hi I understand, due to DMCA notice you can't keep this repository online, but can you please help me, with where i can find Leetcode api so that i can modify the code locally and use it.

Thanks :)

**Comment by 31b4** [comment]
If i would share it here, there would be no point of me shutting this extension down :), sorry i cant

**Comment by AkashKumarSingh11032001** [comment]
Ooh right, so can we connect to some other more secure platform (like discord telegram)?

**Comment by 31b4** [comment]
no
