### ISSUE TITLE
Catching the error like this when I am trying to use this

### ISSUE THREAD

**Issue by ksvr1899** [31b4/Leetcode-Premium-Bypass#121]
function setTextToElement(data) { 
    let strings = data["values"]
    for(let i =0; i <= strings.length-1; i ++) { 
        let text = strings[i][0] + ": " + strings[i][1]
        let element = getSpan(text)
        let parent = document.getElementById("data-update-data")
        parent.appendChild(element)

**Comment by 31b4** [comment]
#99
