### ISSUE TITLE
leet code bypass not working

### ISSUE THREAD

**Issue by Shekhar010** [31b4/Leetcode-Premium-Bypass#125]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
Context
https://leetcode.com/problemset/?page=1
Stack Trace

line 931  : 
let t = {};
                for (let n = 0; n <= e.length - 1; n++) {
                    let i = e[n][0],
                        a = e[n][1];
                    t[i] = a, this.cachedData[i] = n + 1
                }
                return t
            }

**Comment by 31b4** [comment]
#99
