### ISSUE TITLE
Plugin Not working of LeetCode ByPass

### ISSUE THREAD

**Issue by Antique-Creator** [31b4/Leetcode-Premium-Bypass#137]
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/68773679/1ea9f889-f703-422b-bb61-bf74f1cafa6e)

**Comment by 31b4** [comment]
#99

**Comment by Antique-Creator** [comment]
Is there any alternative because leetcode charges are very very very very very very very high.

**Comment by 31b4** [comment]
You can collect leetcode coins to buy a month of premium
