### ISSUE TITLE
Not Working On Leetcode

### ISSUE THREAD

**Issue by wittedtech** [31b4/Leetcode-Premium-Bypass#144]
Device : MacBook Air
Browser : Chrome 

Followed every step mention in the readme.md but still not working over on Leetcode.
None of the premium features are available to use.
Tried Refreshing , Reinstalling multiple times.
![Screenshot 2024-05-23 at 9 00 07 PM](https://github.com/31b4/Leetcode-Premium-Bypass/assets/81770777/bb8b48ce-d87b-4c52-a019-7a76aa78f2f3)

**Comment by Deepak9011** [comment]
same here

**Comment by 31b4** [comment]
#99
