### ISSUE TITLE
Why does this extension need to view my browsing history?

### ISSUE THREAD

**Issue by frank-monkey** [31b4/Leetcode-Premium-Bypass#18]
![pic-selected-231124-1455-17](https://github.com/31b4/Leetcode-Premium-Bypass/assets/86938002/792b091d-f4f4-411c-a16c-1e8c90316902)

**Comment by 31b4** [comment]
### Hello @frank-monkey , the extension needs permission to tabs to be able to make clickable link in the extensions popup menu
<img width="410" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/36c0a48c-f4e5-48c8-b2ba-c9529026733c">


Im sorry for the confusion, feel free to remove "tabs" permission in the manifest.json file, it wont affect the unlocker.
https://github.com/31b4/Leetcode-Premium-Bypass/blob/ae7a0515f052e046ab88b451e931c7335b631660/manifest.json#L5
I will try to find another solution to make popup links clickable, and i will make a new release without "tabs" permission. Sorry again for the confusion.

here is the only usage on that permission:
https://github.com/31b4/Leetcode-Premium-Bypass/blob/ae7a0515f052e046ab88b451e931c7335b631660/dist/extensionPopupManager.js#L29

**Comment by frank-monkey** [comment]
Thank you for the response, understood
