### ISSUE TITLE
Not able to view Edirotial Sample Code

### ISSUE THREAD

**Issue by pink-flames** [31b4/Leetcode-Premium-Bypass#19]
Hi 31b4, would you be able to add this feature?
The smaple code in editorial page is not working as shown below.
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/150642398/7f05b713-ea53-41e6-8bda-be9079389cc8)

Your work is really helpful. I really appreciate this.

**Comment by 31b4** [comment]
Hey @pink-flames, 


Can you provide with more information, i dont really get your suggestion,

in editorial codeblocks are working for me
<img width="1252" alt="Screenshot 2023-11-27 at 16 53 53" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/1efe4edd-c7e4-4934-9c55-6520242270e5">

How can i get "This Playground is Unavailable" error?

**Comment by praveen027** [comment]
Thanks @31b4 refer the following link: https://leetcode.com/problems/insert-delete-getrandom-o1/?envType=study-plan-v2&envId=top-interview-150

**Comment by 31b4** [comment]
Hey @praveen027,

This feature was already added, it was just outdated for this problem, i've updated the database with the new playground, now you should e able the see it. If you are running your own database with google sheets api, here you can download the updated one: https://github.com/31b4/Leetcode-Premium-Bypass/tree/database

Please if you see more outdated editorials, let me know.

**Comment by vvv1ll** [comment]
Hi @31b4, I noticed this question also needs to be updated for the "This Playground is Unavailable" error: https://leetcode.com/problems/design-linked-list/description/
