### ISSUE TITLE
Some companies problems are not displayed

### ISSUE THREAD

**Issue by R3x4r** [31b4/Leetcode-Premium-Bypass#20]
For example, extension not showing problems for Tinkoff/Ozon/Avito companies(attached screenshot)
After click on company name, there is infinite scrolling element instead of a table with problems list.

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/152293216/638d2cbb-d448-4661-b156-d102ccd02daa)

I can assume that this is due to the fact that there is no data on these companies in the google sheet document with which the extension interacts.
So, could you update the list of companies/tasks so that you can view the company's tasks of interest, or at least share them here(if you have the data ofc) :)

**Comment by 31b4** [comment]
@R3x4r, you are right, the excel sheet is outdated, the old data fetcher is outdated so i cant export all the dates, i might fix it in the future. Until then here is 

## Tinkoff
<img width="800" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/5d1582ad-1ad1-4ac1-a30c-73d10f0def5c">

## Ozon
<img width="842" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/433e662c-7bcf-43b5-ad85-9f04a3a5b97d">

## Avito
<img width="812" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/90bdcef3-bc9f-4179-aa3d-760871882bb2">
