### ISSUE TITLE
[Follow-up]Unavailable Editorial Code in following questions

### ISSUE THREAD

**Issue by praveen027** [31b4/Leetcode-Premium-Bypass#24]
Hi, thanks for creating this repository, this is the follow-up issue of #19, some more editorials have playgrounds that are not available.

Here are the questions: 

- https://leetcode.com/problems/candy/
- https://leetcode.com/problems/course-schedule
- https://leetcode.com/problems/container-with-most-water
- https://leetcode.com/problems/group-anagrams/
- https://leetcode.com/problems/insert-interval/
- https://leetcode.com/problems/minimum-path-sum/
- https://leetcode.com/problems/sum-root-to-leaf-numbers/
- https://leetcode.com/problems/first-missing-positive/
- https://leetcode.com/problems/number-of-operations-to-make-network-connected
- https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/
- https://leetcode.com/problems/reaching-points/

Can you please update them too ?

**Comment by 31b4** [comment]
@praveen027 Done, thanks for the feedback.

If you like the extension please leave a star on my repo.

**Comment by praveen027** [comment]
Thanks, sure !!
