### ISSUE TITLE
Does not bypass premium locked problems per company

### ISSUE THREAD

**Issue by Pranavhd** [31b4/Leetcode-Premium-Bypass#25]
Try to first find company specific problems
next click on a problem that is premium locked
doesnt open

e.g. : https://leetcode.com/problems/valid-word-abbreviation/description/

**Comment by nkjag** [comment]
Check the lint code :

The same problem you will get in the lint code

https://www.lintcode.com/problem/637/#:~:text=Where%201%20means%20one%20character,%3D%20%22i12iz4n%22%20Output%20%3A%20true

**Comment by 31b4** [comment]
Hi @Pranavhd, 
Step 1: search for it 
<img width="999" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/50ecc3f7-28b9-4a58-b03c-ae3fb9aa9381">
Step 2: refresh the page
<img width="1029" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/c3280b4f-91f7-4a3a-a312-8c9c6c14cc14">
Step 3: click on it
<img width="1141" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/f3f35a6f-12b1-4373-941d-99cae9c3b709">

**Comment by 31b4** [comment]
@Pranavhd, @nkjag if you like this extension, please leave a star on this repo
https://github.com/31b4/Leetcode-Premium-Bypass
