### ISSUE TITLE
Updated Questions?

### ISSUE THREAD

**Issue by Arpityadav** [31b4/Leetcode-Premium-Bypass#26]
Are the recently asked questions updated? Because it does not seem like they are. If they are not, please update the recently asked interview questions. Or tell us some other way to access the list of recently asked company questions. 

PS: Thank you for maintaining the extension.

**Comment by 31b4** [comment]
@Arpityadav Sadly the [LeetcodeScrapper](https://github.com/Edwardsoen/LeetcodeScrapper) is outdated, i didnt fix it, or made a new one. All i can do now is manually upload a few question to the database, if you tell me which one you would like to see.

**Comment by akshaychavan7** [comment]
Can you update the questions for Goldman Sachs?

**Comment by Arpityadav** [comment]
@31b4 can you please update recently asked interview questions of microsoft? Would be highly appreciated!

**Comment by 31b4** [comment]
hey @Arpityadav, send me the links and ill update them

**Comment by Arpityadav** [comment]
@31b4

**Comment by Arpityadav** [comment]
@31b4 this is the link: https://leetcode.com/company/microsoft . Just need the top 50 6 months questions. if its too much work, Just send me ss of the questions list of last 6 months question by frequency.

**Comment by 31b4** [comment]
@Arpityadav 
<img width="783" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/d23d5c70-6cb7-4dcb-8579-a1cbbe6c07bc">
i think most of them is in my database, if any of the editorial or premium question isnt working, please let me know

**Comment by abhinavms** [comment]
@31b4 Thanks a lot for maintaining the extension.

Would it be possible to share the last 6 months asked questions from Google? (https://leetcode.com/company/google). I would greatly appreciate it.

**Comment by 31b4** [comment]
@abhinavms 
<img width="895" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/f34260f4-90f1-466f-8b6e-b0974592fb6a">
<img width="866" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/f9e7facd-d860-456e-9224-a0fbff8fe345">
<img width="959" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/dc37af2a-fc87-475e-8a81-0dbcbad80672">
