### ISSUE TITLE
premium leetcode questions are not accessible

### ISSUE THREAD

**Issue by realabhijeet** [31b4/Leetcode-Premium-Bypass#28]
I am not able to access premium leetcode questions

**Comment by realabhijeet** [comment]
I downloaded the 1.1.1 version and not able to access premium leetcode questions

**Comment by 31b4** [comment]
@realabhijeet, did you follow the tutorial?https://www.youtube.com/watch?v=5oZMsPbBljo

**Comment by realabhijeet** [comment]
I mean I can view the question but writing code and submitting option is
not coming for premium questions. Only the problem Statement is visible

**Comment by 31b4** [comment]
@realabhijeet yes, thats all this extension does

**Comment by realabhijeet** [comment]
Okay.
By the way thanks for the extension it really helped me a lot . You did a
great work 😊😊
