### ISSUE TITLE
i was not able to acces the premium questions can u pls help

### ISSUE THREAD

**Issue by kotharamya99** [31b4/Leetcode-Premium-Bypass#29]

**Comment by 31b4** [comment]
@kotharamya99 did you follow the tutorial?https://www.youtube.com/watch?v=5oZMsPbBljo

**Comment by kotharamya99** [comment]
Can we also get the locked questions

**Comment by 31b4** [comment]
@kotharamya99 yes if u folloe the tutorial

**Comment by kotharamya99** [comment]
Thanks, I will!

**Comment by 31b4** [comment]
@kotharamya99 let me know if you managed to make it work.

**Comment by kotharamya99** [comment]
Yes, it worked.thank you so much

**Comment by 31b4** [comment]
@kotharamya99 amazing, if you like the extension, please leave a star on this repo
