### ISSUE TITLE
"Alien dictionary" Leetcode question in not opening......

### ISSUE THREAD

**Issue by parth910f** [31b4/Leetcode-Premium-Bypass#31]
Here is the link of that question.....
---------------------------------------------------
https://leetcode.com/problems/alien-dictionary/
---------------------------------------------------

Screenshot
![Screenshot 2024-01-07 034129](https://github.com/31b4/Leetcode-Premium-Bypass/assets/140676230/a52b80ae-4796-46a1-975e-a53a689e03c6)

**Comment by 31b4** [comment]
@parth910f it is opening for me, try this link (refresh if needed)
https://leetcode.com/problemset/?search=269&page=1

<img width="1226" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/9d27571b-c644-426c-acf3-46160079ce4b">

make sure to follow the [tutorial](https://www.youtube.com/watch?v=tARc8QI5AnE&t=35s)
