### ISSUE TITLE
In many questions editorials is not opening properly 

### ISSUE THREAD

**Issue by Sujal20031218** [31b4/Leetcode-Premium-Bypass#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
@Sujal20031218 thanks for the detailed bug description, for me editorial working properly in many cases.

If you could help me which ones of the 'many' are not opening properly, that would be helpful and i could fix it.

**Comment by pratham-agg54** [comment]
Even I am not getting the editorials in any of the questions. For example, <https://leetcode.com/problems/palindrome-partitioning-ii/description/>

**Comment by Sujal20031218** [comment]
https://leetcode.com/problems/first-missing-positive/editorial/
there are many one of them you can try this

**Comment by 31b4** [comment]
<img width="1460" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/be6fb6cc-6494-40ea-a9a7-d88c9c11c678">
@Sujal20031218 Its working for me, make sure to revert to split view mode, here is how: #14
