### ISSUE TITLE
https://leetcode.com/subscribe/?ref=ql_ct&company=facebook&eventName=company_slug&event=facebook

### ISSUE THREAD

**Issue by btsoffice** [31b4/Leetcode-Premium-Bypass#36]
It takes me to the payment page instead of showing facebook interview questions.

**Comment by 31b4** [comment]
Yes this links is redirecting to payment page, only click on the company when its green
use this link: https://leetcode.com/problemset/
<img width="1310" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/7834e38b-9220-4f6a-812e-505273690106">
