### ISSUE TITLE
Error cant load unpacked

### ISSUE THREAD

**Issue by mohdtalha7086** [31b4/Leetcode-Premium-Bypass#37]
Im not able to load unpack coz the systems sending this error:
Could not load icon 'assets/logo.png' specified in 'icons'.
Could not load manifest.

**Comment by RockingThor** [comment]
Can you please share an image of the error?

**Comment by 31b4** [comment]
@mohdtalha7086 try cloning the newest version again, and if the error is still showing, please send a screenshot of it.

**Comment by 31b4** [comment]
@mohdtalha7086 here is how to solve it: #42 
let me know if its working

**Comment by 31b4** [comment]
@RockingThor  a star on this repo is much appreciated.

Btw can you tell me how did you find this repo?

**Comment by RockingThor** [comment]
> @RockingThor  a star on this repo is much appreciated.
> 
> Btw can you tell me how did you find this repo?

Already started. Got to know about it from a YouTube shorts video.

**Comment by 31b4** [comment]
@RockingThor thank you!, can you link me that video if you still have it?

**Comment by RockingThor** [comment]
> @RockingThor thank you!, can you link me that video if you still have it?

Here it is
https://www.youtube.com/shorts/Jjim_YK91PI
