### ISSUE TITLE
Subscribe to unlock display when open premium question

### ISSUE THREAD

**Issue by mistrytejasm** [31b4/Leetcode-Premium-Bypass#38]
when I select Companie and after select Question it says Subscribe to unlock 
![Screenshot 2024-01-18 095540](https://github.com/31b4/Leetcode-Premium-Bypass/assets/147829613/ec30fb5e-b7d3-4c6c-bdc2-a208f19147de)

**Comment by M4X1M4S** [comment]
Same is happening with me.
![Screenshot (18)](https://github.com/31b4/Leetcode-Premium-Bypass/assets/99235816/066edfb2-ccc1-41d0-973d-e44215c3e3c3)

**Comment by knaeeim** [comment]
![Screenshot 2024-01-18 at 1 43 56 PM](https://github.com/31b4/Leetcode-Premium-Bypass/assets/106581785/02c3b832-723e-4c41-b3cc-49b3f9b23b63)
### I saw a green bar and the frequency is also green but I can enter the problem which is not premium but I can't enter which is premium. then show like this. How can I solve this problem...,

**Comment by techsamy** [comment]
same

**Comment by 31b4** [comment]
@knaeeim what browser are you using, it could be the problem.

**Comment by 31b4** [comment]
> when I select Companie and after select Question it says Subscribe to unlock ![Screenshot 2024-01-18 095540](https://private-user-images.githubusercontent.com/147829613/297614025-ec30fb5e-b7d3-4c6c-bdc2-a208f19147de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODA0NzMsIm5iZiI6MTcwNTU4MDE3MywicGF0aCI6Ii8xNDc4Mjk2MTMvMjk3NjE0MDI1LWVjMzBmYjVlLWI3ZDMtNGM2Yy1iZGMyLWEyMDhmMTkxNDdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxMjE2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODZiNDc5MDNkNWEzNWM5YWYzODViZGNmNmE5ZWU4NzE2OWQzYWE2YzcxYTAwZWE1MTU3YTY5YTBmN2QyMWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJwx-M50bxuoqjNZqzQX2-cVL0UaaFQhJNtFipAe9Hw)

It should work @mistrytejasm can you tell me more about the problem?
- browser
- which puzzle
- everything else is working?

**Comment by knaeeim** [comment]
> @knaeeim what browser are you using, it could be the problem.

Google Chrome

**Comment by mistrytejasm** [comment]
@31b4  
I use the Google Chrome browser. Sometimes premium questions are accessible and sometimes show Subscribe to unlock.
This message mostly shows when I try to access Facebook premium questions. 
when I try other companies like Apple, oracle, google, and Microsoft it works fine.

**Comment by knaeeim** [comment]
> Oh i got it. @knaeeim 
> 
> Se basically when you click on the problem its directing your the the problem by link and if the problem is premium you cant view it.
> 
> Here is how to solve it:
> 1. search for the problem
> 2. refresh the page
> 3. wait until the problem is green (if its premium)
> 4. click on it and it should work
> 
> Let me know if its working
> 

and another things is editorial is not working is there any tricks to open editorial?  

Thank you for clarifying the issues.

**Comment by 31b4** [comment]
@knaeeim here is how: https://github.com/31b4/Leetcode-Premium-Bypass/issues/14

**Comment by 31b4** [comment]
> Se basically when you click on the problem its directing your the the problem by link and if the problem is premium you cant view it.
> 
> Here is how to solve it:
> 
> 1. search for the problem
> 2. refresh the page
> 3. wait until the problem is green (if its premium)
> 4. click on it and it should work
> 
> Let me know if its working

@mistrytejasm read this:
So basically when you click on the problem its directing your the the problem by link and if the problem is premium you cant view it.

Here is how to solve it:

search for the problem
refresh the page
wait until the problem is green (if its premium)
click on it and it should work
Let me know if its working

**Comment by mistrytejasm** [comment]
> > Se basically when you click on the problem its directing your the the problem by link and if the problem is premium you cant view it.
> > Here is how to solve it:
> > 
> > 1. search for the problem
> > 2. refresh the page
> > 3. wait until the problem is green (if its premium)
> > 4. click on it and it should work
> > 
> > Let me know if its working
> 
> @mistrytejasm read this: So basically when you click on the problem its directing your the the problem by link and if the problem is premium you cant view it.
> 
> Here is how to solve it:
> 
> search for the problem refresh the page wait until the problem is green (if its premium) click on it and it should work Let me know if its working

I have followed the above instructions but it shows only question there is no place to write the code.
![Screenshot 2024-01-18 181240](https://github.com/31b4/Leetcode-Premium-Bypass/assets/147829613/6cf45815-56b4-4087-9685-1939bab744cf)
