### ISSUE TITLE
Unable to view Question

### ISSUE THREAD

**Issue by Ayush-224** [31b4/Leetcode-Premium-Bypass#39]
Premium questions is still not accessible without subscription.

**Comment by techsamy** [comment]
same here, unable to click on premium questions

**Comment by 31b4** [comment]
@techsamy @Ayush-224 It's still working for me, can you tell me more about the problem?
- what browser are you using?
- which puzzle?
- other features are working?

**Comment by Ayush-224** [comment]
Well I am using Google Chrome and when I click on premium questions to open editor  it says to subscribe and open payment page,

**Comment by Gourav-21** [comment]
@Ayush-224 @techsamy 

you cannot directly open the premium question by link as will directly take you to the subscribe to premium page

so seach the question in the problemset and then click on it when it appears green and you will get the question 

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/deb3a55d-0dad-41c6-89ee-43a6894f9e9c)

## then the question appears
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/1020cdfb-8984-46aa-81a0-68fb12f85244)

**Comment by Ayush-224** [comment]
@Gourav-21 the thing is question is opening in the modal but here I am telling about the editor, question isn't opening in editor like the normal questions.

**Comment by Gourav-21** [comment]
@Ayush-224 that's not possible 😂 
you have to buy premium for that, the most we can do is show you the question.

**Comment by 31b4** [comment]
> @Gourav-21 the thing is question is opening in the modal but here I am telling about the editor, question isn't opening in editor like the normal questions.
> 
> 
> 
> 

Can you send screenshot where and when?

**Comment by Ayush-224** [comment]
@Gourav-21 well I knew that but I am suggesting how good will it be....🙄😂

**Comment by Gourav-21** [comment]
@Ayush-224 😂i wish we could but even if we managed to hack the backend and enable it somehow, leetcode will sue shit out of us 🤧🫂

**Comment by Gourav-21** [comment]
@31b4 i think we can use these screenshots to guide people how to see premium questions 

> you cannot directly open the premium question by link as will directly take you to the subscribe to premium page
> 
> so seach the question in the problemset and then click on it when it appears green and you will get the question
> 
> ![image](https://private-user-images.githubusercontent.com/107918791/297805612-deb3a55d-0dad-41c6-89ee-43a6894f9e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTM3OTUsIm5iZiI6MTcwNTYxMzQ5NSwicGF0aCI6Ii8xMDc5MTg3OTEvMjk3ODA1NjEyLWRlYjNhNTVkLTBkYWQtNDFjNi04OWVlLTQzYTY4OTRmOWU5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTMxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGQ0ZDBlNWQ5NzMyZDBmZGQ3NWJhZjRhYjcxNWMzYTcyMGY0OGFkMmNmMzE5YTE1NmNlODAwOWFlZGJlOWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vByWVOV6PmALDo7NCcWXP_4gAqH9V2N6LNKQXnX2YtM)
> 
> ## then the question appears
> ![image](https://private-user-images.githubusercontent.com/107918791/297806722-1020cdfb-8984-46aa-81a0-68fb12f85244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTM3OTUsIm5iZiI6MTcwNTYxMzQ5NSwicGF0aCI6Ii8xMDc5MTg3OTEvMjk3ODA2NzIyLTEwMjBjZGZiLTg5ODQtNDZhYS04MWEwLTY4ZmIxMmY4NTI0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTMxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjYyODViZDlkYWQyYjY3OTE0OTkyYTI3Y2I5N2Q1M2I1ZjgxYWI0OWFlODZjYmE4NzBmOGJjMmJiODQwM2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kxh-cMvEXnmYqxSzRfZksvkSomIFsgp8HKH5o8crxCY)

**Comment by Ayush-224** [comment]
@Gourav-21 yup! It is what it is....
