### ISSUE TITLE
Failed to load the extension.

### ISSUE THREAD

**Issue by RanveerRathour** [31b4/Leetcode-Premium-Bypass#40]
failed to load the manifest file
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/109944269/7cfd8e5e-cbb9-469c-9f79-b9f2406ef503)

**Comment by 31b4** [comment]
@RanveerRathour here is how to solve it: #42 
let me know if its working

**Comment by RanveerRathour** [comment]
> @RanveerRathour here is how to solve it: #42 let me know if its working

thanks, It's working now...

**Comment by 31b4** [comment]
@RanveerRathour a star on this repo is much appreciated.

Btw can you tell me how did you find this repo?
