### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by shithead999** [31b4/Leetcode-Premium-Bypass#41]
**Describe the bug**
Manifest File is missing or unreadable 

**To Reproduce**
1. Go to 'Extension'
2. Click on 'Developer Mode'
3. Select  'Load Unpack'
4. Choose the folder
5. See the error

**Expected behavior**
The Extension should work properly , it is not even loading in the first place

**Screenshots**
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/111310463/918c2880-1bf8-43fc-94bc-cbe3b6330306)

**Desktop (please complete the following information): Chrome**

**Comment by 31b4** [comment]
@shithead999 please check the folder if its containing the manifest file correctly, if yes and its still not working try another way of cloning the repo https://github.com/31b4/Leetcode-Premium-Bypass/blob/main/manifest.json

**Comment by Gourav-21** [comment]
@shithead999 hey you probably did some mistake whle loading it, follow this video https://www.youtube.com/watch?v=5oZMsPbBljo&ab_channel=31b4 

if it still doesnt help tell us

**Comment by shithead999** [comment]
The issue still persist

**Comment by 31b4** [comment]
@shithead999 we solved the issue, read here #42

**Comment by 31b4** [comment]
Let me know if its working

**Comment by shithead999** [comment]
Yup, its working now

**Comment by Gourav-21** [comment]
@shithead999 so the main problem was u loaded it wrong way right??
can u suggest what can we do so people like you dont have any problem understanding how to load it??

**Comment by 31b4** [comment]
@shithead999 a star on this repo is much appreciated.

Btw can you tell me how did you find this repo?

**Comment by shithead999** [comment]
Sure,
Was surfing GitHub for a leetcode solution 😅
