### ISSUE TITLE
getting error in unlocking leetcode premium

### ISSUE THREAD

**Issue by RupeshSangoju** [31b4/Leetcode-Premium-Bypass#43]
**Describe the bug**
getting error in unlocking leetcode premium

**Screenshots**
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/106753280/c268c56b-3666-4867-8e43-5aa0771780c9)

**Desktop (please complete the following information):**
 - Microsoft edge

**Comment by Gourav-21** [comment]
u loaded it wrong 
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/d5b76b8c-b0f1-4f6e-9b07-dbd6900d77a5)
select this one

**Comment by 31b4** [comment]
@RupeshSangoju and read #42

**Comment by RupeshSangoju** [comment]
thank u so much its working now

**Comment by 31b4** [comment]
@RupeshSangoju a star on this repo is much appreciated.

Btw can you tell me how did you find this repo?

**Comment by RupeshSangoju** [comment]
> @RupeshSangoju a star on this repo is much appreciated.
> 
> Btw can you tell me how did you find this repo?

i already stared it. I found this on twitter
