### ISSUE TITLE
Editorial not coming

### ISSUE THREAD

**Issue by UddeshyaSeth** [31b4/Leetcode-Premium-Bypass#46]
Editorial not coming on the opening of the premium question, only prompt/question statement is coming.
How to overcome this issue.

**Comment by 31b4** [comment]
Hey, here is how to fix @UddeshyaSeth : https://github.com/31b4/Leetcode-Premium-Bypass/issues/14

**Comment by Gourav-21** [comment]
@UddeshyaSeth sorry that's not possible 😂
you have to buy premium for that, the most we can do is show you the question.

and believe me you dont need that perticular question, the only thing you need is the pattern so just search for the pattern that question uses and you will get questions like that
