### ISSUE TITLE
Unable to run extension in MAC Extension not working in Mac

### ISSUE THREAD

**Issue by surbhi498** [31b4/Leetcode-Premium-Bypass#48]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
@surbhi498 fill out the bug report, i can't do anything with this, it is clearly working on mac. Please write an issue properly.
<img width="556" alt="Screenshot 2024-01-19 at 09 38 36" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/0c2a3fd2-bae5-4d33-889e-a0853798e66b">
