### ISSUE TITLE
Some Premium Question are unable to open

### ISSUE THREAD

**Issue by surbhi498** [31b4/Leetcode-Premium-Bypass#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
@surbhi498 bro explain it in a new issue. I CANT do anything with it. Explain where, when, how and which of the "some" isn't working. I'm not gonna be able to fix the "some question", without knowing which ones, and when.

Open a new issue, with a detailed issue.
