### ISSUE TITLE
Not Able To Use Some Premium Features

### ISSUE THREAD

**Issue by Harshit-BCS** [31b4/Leetcode-Premium-Bypass#50]
Extension is completely setup but i am not able to use some premium feature like : 

- Debugger In Code Editor
- Editorial of a Question 
- On Clicking over premium button it's asking for Payment.
- 
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/81770777/4cd705fa-3158-4338-a688-4a8491f3137e)
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/81770777/cba034bb-4bdd-4e7e-96ec-fc9ebb6374df)

**Comment by 31b4** [comment]
# Hey, thanks for you suggestions. 
Yes these features are currently not available, but we gonna try to enable them in the future.

The editorial is working, you just need to revert it back to the split UI, see here: #14 
Also we are trying to fix it to work on the new dynamic UI, but it might take some time since its too complicated.

**Comment by theboywholived** [comment]
Hey @31b4 - I installed the extension just now and cleared cookies etc also. I can see the green lines but not able to see any editorial or access any premium questions.

**Comment by 31b4** [comment]
@theboywholived did you followed the tutorial? https://www.youtube.com/watch?v=tARc8QI5AnE

**Comment by theboywholived** [comment]
Yes @31b4 - I have followed the steps.
Attached recording below.

https://github.com/31b4/Leetcode-Premium-Bypass/assets/13106828/b085f043-1c9d-49e4-89d5-074bb9f3a990

**Comment by 31b4** [comment]
@theboywholived click on the Description menu before refreshing the page.
Here is how:

https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/ca5a0e9d-79a7-493c-9f5f-c38e330082e5

**Comment by Gourav-21** [comment]
hi @theboywholived , the extension needs time to analyse the page and load the buttons, you are just switching too fast between different things thats why it is not able to load

change the ui to split ui 
go to this link https://leetcode.com/problems/binary-tree-right-side-view/description/ in description page
and just wait for literally 1 sec and you will see the editotial button green

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/f5ac9591-a032-4403-8311-dbe0d11ce51d)

**Comment by ksvr1899** [comment]
Hey, previously It worked fine in my computer but now it is not working what could be the reason??

**Comment by 31b4** [comment]
#99
