### ISSUE TITLE
Can someone explain me this?

### ISSUE THREAD

**Issue by kishan2k2** [31b4/Leetcode-Premium-Bypass#51]
Can some one explain to me how did they build this extension i.e. providing premium content for free, Iam very much interested in learning this. Can someone please?

**Comment by 31b4** [comment]
# Hey @kishan2k2,

### 1. Database Setup:

- The extension has a database that stores questions.
- Questions are exported from the leetcode website (with a custom scalper program) and stored in a format that the extension can easily retrieve.
### 2. User Interaction:

- When a user requests a premium question, they trigger an action, such as clicking on the question or interacting with the website.
### 3. Database Retrieval:

- The extension, upon receiving the user's request, retrieves the corresponding premium question from its database.
### 4. HTML Injection:

- Once the premium question is retrieved, the extension dynamically injects it into the HTML of the webpage the user is currently viewing.
- This means the premium question becomes part of the visible content on the webpage.

### See the compiled code here: https://github.com/31b4/Leetcode-Premium-Bypass/blob/main/dist/main.js

**Comment by man0xff** [comment]
How is it possible? Doesn't LeetCode site check premium subscription on the backend?

**Comment by 31b4** [comment]
Its not unlocking the premium features, as i said its getting the datas from a exported database and only injecting it to the buttons, so when you click on a question, the extension disabled it, and made a new onClick() for the button.

**Comment by kishan2k2** [comment]
And how does leetcode accept the solution, correct me if I am wrong, and sorry in advance for my naivety.

I believe that HTML injection should be a static thing like how we can change the HTML content using the inspect element, but once we refresh the page everything is gone.

I agree that we can inject the question into the webpage but how are we able to submit the question, I mean only premium users should be able to answer the premium questions right?

**Comment by 31b4** [comment]
You are not able to submit, that would be way too complicated to make.

**Comment by kishan2k2** [comment]
Understandable, And thanks for replying so fast. That was unexpected.
