### ISSUE TITLE
Leetcode-Premium Bypass

### ISSUE THREAD

**Issue by Prashantgupta07** [31b4/Leetcode-Premium-Bypass#52]
Failed to load extension
File
~\Downloads\Leetcode-Premium-Bypass-1.1.2
Error
Manifest file is missing or unreadable
Could not load manifest.

Resolve issues.

**Comment by 31b4** [comment]
@Prashantgupta07 #44

**Comment by YashVardhanRaghav** [comment]
Open first folder and then add the folder inside to extension

**Comment by 31b4** [comment]
> Open first folder and then add the folder inside to extension

Yeah it happens with most of windows users😅
