### ISSUE TITLE
leet

### ISSUE THREAD

**Issue by YashVardhanRaghav** [31b4/Leetcode-Premium-Bypass#53]
Its showing frequency as ststed but the questions still remain locked

**Comment by 31b4** [comment]
Can you send a screenshot where and when? @YashVardhanRaghav

**Comment by YashVardhanRaghav** [comment]
![Screenshot (3)](https://github.com/31b4/Leetcode-Premium-Bypass/assets/124517595/a0994ea9-0e1a-430c-88e5-f32f58a7fc0b)
![Screenshot (4)](https://github.com/31b4/Leetcode-Premium-Bypass/assets/124517595/d1734dbd-c721-4b2e-befa-61871f448626)

**Comment by 31b4** [comment]
when you see this you have to refresh the page. @YashVardhanRaghav 
<img width="787" alt="Screenshot 2024-01-19 at 15 52 04" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/454b6ce9-cbea-474a-be3a-98103234181b">
