### ISSUE TITLE
Editorial implementations are not visible

### ISSUE THREAD

**Issue by saicantcode** [31b4/Leetcode-Premium-Bypass#54]
**Describe the bug**
When I click editorial for a subscription problem the implementation solution is not loading with an error.

**Screenshots**
<img width="1422" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/157163098/fa6871ab-92dd-4115-bc7d-eca2f559b23c">

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by 31b4** [comment]
@saicantcode fixed it, check it now.

**Comment by saicantcode** [comment]
https://leetcode.com/problems/set-mismatch/

Still facing same issue 
<img width="1276" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/157163098/32386a91-64ac-4178-aa7c-72313265b7d0">

I see this issue for every problem.

**Comment by 31b4** [comment]
Yes sadly the database is outdated, i will try to update it, but it might take some time.

**Comment by saicantcode** [comment]
let me know if I can help you in some way

**Comment by 31b4** [comment]
@saicantcode sure you can help us, its an open source project.
