### ISSUE TITLE
Using OperaGX browser. Can't access Editorials!

### ISSUE THREAD

**Issue by SaikrishnaLingam** [31b4/Leetcode-Premium-Bypass#56]
I am using this extension in OperaGX browser. I cannot access Editorials to questions. In this case, I opened problem 907, and even after reloading multiple times, I cannot access the Editorial.

**Comment by 31b4** [comment]
Did you try to switch back to split UI?

see here how: #14

**Comment by Gourav-21** [comment]
> Did you try to switch back to split UI?
> 
> see here how: #14

@SaikrishnaLingam follow this but if this stilll doesnt work give us a screenshot
