### ISSUE TITLE
editorial section not working 

### ISSUE THREAD

**Issue by 9oExcuse** [31b4/Leetcode-Premium-Bypass#57]
First of all, kudos to the awesome developer for making a beast of a plugin. All of my features work fine except the editorial section on my brave browser. 
<img width="434" alt="Screenshot 2024-01-20 174850" src="https://github.com/31b4/Leetcode-Premium-i Bypass/assets/118768105/17815ee5-c72c-4386-ac88-ef5e762d90bc">

I didn't try on other browsers because brave has other adblocking features too which makes me stick to it. 
Appreciate the dev to fix it.

**Comment by 31b4** [comment]
Hey @9oExcuse , did you try to use split UI?
see here: #14

**Comment by Gourav-21** [comment]
@9oExcuse hey we cannot see your screenshot to help you, please reupload it 
and if you are using dynamic ui then the editotial wont work 
so go this 

> Hey @9oExcuse , did you try to use split UI? see here: #14

**Comment by 9oExcuse** [comment]
great it's working now after switching off the dynamic UI. thanks for the solution.
