### ISSUE TITLE
Ilustrations slides and code section is not working in Editorial section

### ISSUE THREAD

**Issue by RishabhSkr** [31b4/Leetcode-Premium-Bypass#58]
**Describe the bug**
Ilustrations slides and code section is not working in Editorial section

**To Reproduce**
when I go to editorial section previous section it is not showing slides illustration and code section playgraound

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
Can you send a screenshot of it? And which problem?

**Comment by mukuljha302** [comment]
@31b4  Same I am also facing unable to open the editor.when i click the question after refreshing it does not open the code editor

**Comment by 31b4** [comment]
@mukuljha302 use split UI: #14
