### ISSUE TITLE
Any way to access the Explore Cards?

### ISSUE THREAD

**Issue by punmaster100** [31b4/Leetcode-Premium-Bypass#59]
Is there any way to access the company-specific [Explore Cards](https://leetcode.com/explore/)? <br>Getting access to those questions would be great for company-wise prep....
<br>
Also, amazing project, thank you so much for this!

**Comment by 31b4** [comment]
We couldn't make it interactive and without that it wouldn't be that useful, but im gonna save this suggestion. Maybe someday

**Comment by codewithvamshi** [comment]
> We couldn't make it interactive and without that it wouldn't be that useful, but im gonna save this suggestion. Maybe someday

hey it is not working man this extension can we use code in another file changing names will be works right?
can u please update working code?

**Comment by 31b4** [comment]
#99
