### ISSUE TITLE
Not able to check the Editorial section.

### ISSUE THREAD

**Issue by Laksmi1940** [31b4/Leetcode-Premium-Bypass#6]
Whenever I try to check the Editorial section, it asks for the premium.

**Comment by 31b4** [comment]
Ive had to disable editorial since the new ui changes fucked up the extension. I might try to fix it soon. @Laksmi1940

**Comment by 31b4** [comment]
@Laksmi1940 Now its working perfectly with companies button aswell, check the lates release: https://github.com/31b4/Leetcode-Premium-Bypass/releases/tag/1.1.0

**Comment by Laksmi1940** [comment]
Thank you so much. Appreciated your effort. However, When I select only the premium questions(from setting), it's not working. After I select a particular question, It's showing "No data". Attached the screenshot. 

<img width="337" alt="Screenshot1" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/26248147/801353ad-e910-480d-ad86-3256cdceb9ce">


<img width="907" alt="Screenshot" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/26248147/e9d698f5-b4ef-4828-8d0b-d0918f020b5b">

**Comment by Laksmi1940** [comment]
For a few Questions even if the Company tag is in Green in color, the editorial section asks for Premium. I have attached the screenshots.

<img width="473" alt="1" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/26248147/becfad69-f3ca-4ccc-a632-d6039e9e7cd1">

<img width="474" alt="2" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/26248147/08ccaede-3943-437e-9555-0aba8b5b5a5c">

**Comment by 31b4** [comment]
### Hey @Laksmi1940 

1. The database is limited to 2759. and i might not be able to update it, but i will try.
2. For now editorial isnt working for premium question but this is what im aiming to fix next.
3. make sure to refresh the page when bot premium and video icon is visible. (We gonna try to find a solution for this aswell, thank you for the feedbacks)
<img width="126" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/c9f104bd-efed-4907-8589-9743b0c88112"><br>
<img width="525" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/940625db-c0a9-41ea-9858-faffab49d18b">

**Comment by Laksmi1940** [comment]
Thanks. Now I got it. By refreshing the page I am able to check the editorial.

**Comment by 31b4** [comment]
Super @Laksmi1940, if you like the extension please give a star to the repo, its much appreciated

**Comment by Laksmi1940** [comment]
Done!! Thanks.
