### ISSUE TITLE
Extension for firefox

### ISSUE THREAD

**Issue by Prajwalg19** [31b4/Leetcode-Premium-Bypass#60]
Requesting for firefox extension

**Comment by 31b4** [comment]
It's coming soon, save this repo!

**Comment by godwin-jg** [comment]
its actually working now.
(for those who done know : you can add by going to about:debugging in firefox and select the manifest.json file)

**Comment by Prajwalg19** [comment]
Works but it is just a temporary workover, the extension doesn't persist after the browser is restarted
