### ISSUE TITLE
Extension is not getting loaded

### ISSUE THREAD

**Issue by chatterjee2407** [31b4/Leetcode-Premium-Bypass#62]
![WhatsApp Image 2024-01-21 at 13 50 59_48527c9d](https://github.com/31b4/Leetcode-Premium-Bypass/assets/72260266/9faab8a0-2e1e-4746-aaf2-525e658286a8)

When loading unpacked extensions it then showing the problem of any file is not present "Manifest" named file

**Comment by 31b4** [comment]
@chatterjee2407, make sure to unzip it properly

see how here: #44
