### ISSUE TITLE
Unlimited loading for "The Trade Desk" Company questions

### ISSUE THREAD

**Issue by 1TusharSharma1** [31b4/Leetcode-Premium-Bypass#64]
**Describe the bug**

When I search question from the "Trending Companies" Tab, On home screen. The questions take unlimited time to load.

**To Reproduce**
1. Go to 'Problem Tab'
2. Click on 'Search bar of Trending Companies' (present on right side)
3. Search for the company "The Trade Desk".
4. Questions take unlimited amount of time to load.

**Expected behavior**

A list of questions should've been displayed.

**Screenshots**
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/91653616/c0ffa1d3-4c57-4f6b-abf5-e03492fbf506)

**Desktop (please complete the following information):**
       Chrome
**Additional context**

**Comment by 31b4** [comment]
Unfortunately, our database is outdated. Make sure to save this repo we gonna update it soon. Thank you for your issue.
