### ISSUE TITLE
Getting Black UI

### ISSUE THREAD

**Issue by Laksmi1940** [31b4/Leetcode-Premium-Bypass#7]
When I select a particular company, (1) I get this black screen. (2) The question is not turning to green color as mentioned.

<img width="883" alt="Screenshot" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/26248147/d08e70f5-4116-4934-b1e5-d55a31d114a5">

**Comment by 31b4** [comment]
1. Leetcode recently did changes to the ui darkmode, so i had to disable white background and made it dark, so darkmode users can see it perfectly. I know lot of users use it in light mode so i'm gonna fix it as soon i can and let you know.

2. Premium problems not turning green where? In the company box or in the problem list at https://leetcode.com/problemset/all/?premium=true&page=1 . Did you refresh the page? Can you provide with more info with this one? It's still working for me. Check my tutorial, it could help https://www.youtube.com/watch?v=5oZMsPbBljo

**Comment by 31b4** [comment]
@Laksmi1940

**Comment by 31b4** [comment]
@Laksmi1940 
✅Fixed the problem 1. https://github.com/31b4/Leetcode-Premium-Bypass/releases/tag/1.0.4

Let me know if its good now, and please provide with more information about the second issue.

**Comment by Laksmi1940** [comment]
I appreciate your effort. Its working now. Thank you so much. I think this current versions(1.0.4) working fine.

**Comment by 31b4** [comment]
@Laksmi1940 stay tuned, we are about to fix companies tag button on problems and editorial
