### ISSUE TITLE
Hi, I am unable to see the entire editorial it is not scrolling down up to end and some images are not loading

### ISSUE THREAD

**Issue by surbhi498** [31b4/Leetcode-Premium-Bypass#70]
<img width="1407" alt="Sum of Subarray Minimum" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/62746024/c3d4e6b6-f9eb-43f6-8351-1a862d38e038">

**Comment by 31b4** [comment]
@surbhi498  Yes, unfortunately, leetcode doesn't let me export these images

I might come up with a solution later.

**Comment by surbhi498** [comment]
I am not able to see entire editorial too it is not scrolling till end. One more, can I also contribute to the codebase of this leetcode premium bypass. You made awesome product.

**Comment by 31b4** [comment]
Of course, this is an open source project. @surbhi498

**Comment by yaten2302** [comment]
Hi @surbhi498, I just wanted to ask that is this issue still there? As on my side, there is no such issue. <br>
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/129659514/efefe896-6b17-4f79-b5de-91c1fe9b94cc)

Also, if this issue still exists, can we collaborate on this please? I would also like to contribute to this project.

**Comment by surbhi498** [comment]
Hi,
Yes, I have still this issue. Yes, we can collaborate on this. We can contribute to this project.

**Comment by yaten2302** [comment]
Thanks @surbhi498 👍
Also, could you please elaborate the issue a bit more, I'm not able to understand it completely.

**Comment by 31b4** [comment]
@yaten2302 only these types of documents are not shown correctly. And since the database is old, we would need to create a new data fetcher to export the updated dated.
<img width="624" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/e8a2a2fb-dbb3-4768-9fc0-fd7c1a52d2fc">

**Comment by yaten2302** [comment]
Hi @31b4, could you please send the link from where you took this screenshot? actually I'm just trying to understand the root cause of the problem<br>
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/129659514/8b95b44f-74b6-426f-9634-c08d227ed3f7)
Also, I apologize if this is creating some kind of trouble, I'm not able to get that why the new div element was created because this question is not a premium one?

**Comment by yaten2302** [comment]
Hi @31b4, could you once again please tell that are you talking about the editorial section? As I'm not able to see anything in the editorial section.<br>
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/129659514/6c718c84-d5c8-4ea9-a79a-f128968b5390)

**Comment by 31b4** [comment]
@yaten2302 
Please make sure to follow to video step by step: https://twitter.com/31b4_/status/1748694097433395416

and change the UI back to SPLIT UI: #14

**Comment by yaten2302** [comment]
Understood, thank you so much 👍 @31b4

**Comment by yaten2302** [comment]
Hi @31b4, I was having some issues while understanding the code, could you please guide that why this api is used? `https://www.google-analytics.com/mp/collect` in the [analyticsManager.js](https://github.com/31b4/Leetcode-Premium-Bypass/blob/main/dist/modules/AnalyticsManager.js)

**Comment by Gourav-21** [comment]
hey @yaten2302, it is used to track the buttons clicks of the extension and give an analytics data of which funtions of the extension are used the most and all

**Comment by yaten2302** [comment]
Hi @Gourav-21, if I've understood correctly, then `analyticsManager.js` file has nothing to do with unlocking the leetcode premium features?

**Comment by Gourav-21** [comment]
@yaten2302 nope and i just wanted to tell you that if you really want to learn how this extension is created, go to the original repo https://github.com/Edwardsoen/Leetcode-Premium-Unlocker because our fork has incomplete files.

that module folder that u see, when compiled generates the main.js file and that is what chrome uses to show you the extension.
so, that module folder is never used and it wasnt even suppose to be there, its a mistake it is there.

Because the main.js is the only thing that the chrome uses, whenever we need to make any change, we make change in that file.

**Comment by Gourav-21** [comment]
@yaten2302 and if u want to contribute to this project, i will suggest you to dont as we have already fixed everything that was possible and now to fix anything further we have to recreate the whole code and the database

however, if you want to try, go to the main.js. it is kind of hard to understand as it is the compiled code

**Comment by yaten2302** [comment]
> @yaten2302 nope and i just wanted to tell you that if you really want to learn how this extension is created, go to the original repo https://github.com/Edwardsoen/Leetcode-Premium-Unlocker because our fork has incomplete files.
> 
> that module folder that u see, when compiled generates the main.js file and that is what chrome uses to show you the extension. so, that module folder is never used and it wasn't even suppose to be there, its a mistake it is there.
> 
> Because the main.js is the only thing that the chrome uses, whenever we need to make any change, we make change in that file.

Hi @Gourav-21, as you told that almost everything in this project has been fixed and for any further changes, the whole code and the database needs to be redesigned. This might create a lot of new problems, which currently don't exist.

Even if I don't contribute to this project, I'm very keen to know how this extension works. It will be really helpful for me if any of the contributor/maintainer could guide me regarding this 🙏. (I'll also try my best to explore about this as much as possible from my side)

**Comment by Gourav-21** [comment]
> This might create a lot of new problems, which currently don't exist.
it wont if we create the whole code base from scratch according to the ui and the reason why this extension doesnt work for dynamic ui is that it was never made for that.

yea feel free to ask any questions you have but let me you this repo has incomplete files and the file we works with `index.js` is the compiled version of many files and undersanding how everything works from that(`index.js`) file is impossible.

but still free to ask any questions

**Comment by yaten2302** [comment]
> > This might create a lot of new problems, which currently don't exist.
> 
> it wont if we create the whole code base from scratch according to the ui and the reason why this extension doesnt work for dynamic ui is that it was never made for that.
> 
> yea feel free to ask any questions you have but let me you this repo has incomplete files and the file we works with `index.js` is the compiled version of many files and undersanding how everything works from that(`index.js`) file is impossible.
> 
> but still free to ask any questions

Hi @Gourav-21, I was having some issues while reading the code in the `main.js` file. As you told that this is a compiled version of many files, but understanding this file is quite challenging. Could you please guide that how to understand this code?

**Comment by Gourav-21** [comment]
yo @yaten2302, this `main.js.LICENSE.txt` file is irrelevant, it does nothing. 

And i just checkout dom purifier in the [original repo](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker) . 
What it does is cleans the data we get from database before we put it in the model (the grey colored box where u see the editorial).

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/107918791/55b55da7-81e7-48c1-b417-68f053a9665a)

[example](https://www.npmjs.com/package/dompurify#some-purification-samples-please) of what it does.

> Could you please guide that how to understand this code? 

you tell me how do i guide u lol and please dont try to understand the `main.js` file 🥹, its not meant for humans to understand and give you brain hemorrhage too

Go to the [original repo](https://github.com/Edwardsoen/Leetcode-Premium-Unlocker) its much more understandable tho
and i m thinking to revamp the codebase soon using the original repo only, so it would be better if we start understanding that.

**Comment by yaten2302** [comment]
Hi @Gourav-21, actually I wasn't aware of this repo - https://github.com/Edwardsoen/Leetcode-Premium-Unlocker. Thanks for the link, I'll surely check it out 👍. Yeah sure, revamping the codebase is a great idea. It will help many to understand the code. Eagerly waiting for it.

**Comment by Gourav-21** [comment]
@yaten2302 fork or download the repos asap, leetcode has sent a notice to take down both the repos

**Comment by yaten2302** [comment]
Hey @Gourav-21, I'll download both the repos by today 👍Thanks for telling.

**Comment by yaten2302** [comment]
Hey @Gourav-21, in this repo, https://github.com/Edwardsoen/Leetcode-Premium-Unlocker, I saw that there is already an Excel sheet present in which all the premium questions and frequencies etc are present. But, if, had there been no such Excel sheet, then was it possible to build this extension?

**Comment by Gourav-21** [comment]
@yaten2302 good to know that you are still trying to understand that repo, once you fully done make me understand it too 😂 
yea, that sheet is the most imp thing, that has all the data. what this extension does is, it just injects the data into the html and displays them. Without that sheet the extension is useless

**Comment by yaten2302** [comment]
Thanks @Gourav-21 for your support. 

Now, I'm able to understand this extension a little bit, I guess I will take some more time to completely understand this completely😅

I just asked this because, I was having an idea of making a similar extension like this, but for `HackerRank`. Like similiar features, but first I thought to understand this repo completely and also take some guidance from you, since you have contributed a lot to this repo.

**Comment by Gourav-21** [comment]
@yaten2302 i m noob 😂 but thats a great idea, you just need the data and its done.😄👍

**Comment by yaten2302** [comment]
Hey @Gourav-21, I also wanted to ask something regarding the `analyticsManager.js` file. In this file, the `POST` request is used to put the data on the website, right?

**Comment by Gourav-21** [comment]
hey @yaten2302, i was busy so couldnt reply lol.

no, its function is to track and send user interactions like button clicks and errors to Google Analytics.

**Comment by yaten2302** [comment]
Hey! @Gourav-21, @31b4, actually I wanted to ask something regarding fetching the data from the google sheets. How can we get our own API key? Like, if we want to do the same thing with different google sheet, then what will be our api key?

**Comment by 31b4** [comment]
You have to host your own database to get your own api key.
