### ISSUE TITLE
Cannot read properties of null 

### ISSUE THREAD

**Issue by skr3178** [31b4/Leetcode-Premium-Bypass#71]
Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
Context
https://leetcode.com/problems/number-of-ships-in-a-rectangle/description/
Stack Trace

![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/79299617/65e3b472-f8ad-4b55-acfe-cedac5780bbd)

**Comment by skr3178** [comment]
unpacking works and adding to extension work for a while and then stops working. 
Have to reupload the package

**Comment by 31b4** [comment]
You have to usi split UI

here is how: #14

**Comment by bcawallah** [comment]
Its Not Working. Could please check this ?
![Screenshot (853)](https://github.com/31b4/Leetcode-Premium-Bypass/assets/121385957/6ab9246b-6754-4c1a-9108-31ec429b1c0c)

**Comment by 31b4** [comment]
click on description, and refresh there @bcawallah, so editorial can turn green

**Comment by Sivasish48** [comment]
1. The error you're encountering, Uncaught TypeError: Cannot read properties of null (reading 'parentNode'), indicates that the expression   this.findElementByTagNameAndInnerHTML("span", "Editorial")   is evaluating to null, and you're trying to access the parentNode property on a null value.

2. To handle this error and prevent it from causing issues, you should check if the result of findElementByTagNameAndInnerHTML is null before trying to access its properties. 

3. May be if it is the case, should I make a PR on it?

**Comment by 31b4** [comment]
@Sivasish48 when you are looking at description tab, the tag of editorial button is different compared to when you are looking at editorial tag. So to let the script find editorial tag correctly you need to be at description tag. 

I might solve this issue today. If you are interested working on it with me dm on discord @31b4

**Comment by Gourav-21** [comment]
@Sivasish48 good to see someone from bbsr contributing to open source but  if u want to contribute to this project, i will suggest you to dont as we have already fixed everything that was possible and now to fix anything further we have to recreate the whole code and the database

however, if you want to try, go to the main.js.
it is kind of hard to understand as it is the compiled code.

**Comment by Sivasish48** [comment]
Thank you for your valuable feedback and for sharing the current status of the project. I appreciate the effort you've put into fixing issues and maintaining the codebase. I'll take a look at the main.js file, as you suggested, and explore the possibilities ( I will reply if there is something that I can). Once again thank you so much for the support and respectful response.

**Comment by Gourav-21** [comment]
ayushman bhava 🖐️,au jadi to contribute kariba chahuchu bhala project re contribute karle to resume re bi add kari haba ta au tu bhot nua jinsa jani bi paribu nahele soi pade 😂🫂

**Comment by Sivasish48** [comment]
where to connect bhai? Sana bhai needs a bada bhai 😂🫂

**Comment by Gourav-21** [comment]
@Sivasish48 discord achi? username - tun_nu

**Comment by Sivasish48** [comment]
> @Sivasish48 discord achi? username - tun_nu

hann bhai donee

**Comment by Gourav-21** [comment]
> > @Sivasish48 discord achi? username - tun_nu
> 
> hann bhai donee

mate kichi asini, sala au kahaku dei delu 😂

**Comment by Sivasish48** [comment]
Done this time sure bhaii 😂
