### ISSUE TITLE
Cannot access questions of Palo Alto Networks

### ISSUE THREAD

**Issue by SiddhiWakchaure** [31b4/Leetcode-Premium-Bypass#72]
**Describe the bug**
When I try to search for the questions of Palo Alto Networks it keeps on loading and doesn't show anything.

**To Reproduce**
1. Go to 'search bar of trending companies' (a right-side box)
2. Search 'Palo Alto Networks'
3. Click on 'Palo Alto Networks'
4. See error (Keeps buffering)

**Expected behavior**
Should show a list of questions

**Desktop (please complete the following information):**
 - Chrome

**Comment by 31b4** [comment]
The current database is outdated. We might update it soon.
