### ISSUE TITLE
Not working, Not showing the tag of the problems

### ISSUE THREAD

**Issue by Kiran-Jadhav200** [31b4/Leetcode-Premium-Bypass#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
It is working, thank you for the detailed issue! @Kiran-Jadhav200

**Comment by Gourav-21** [comment]
hey @Kiran-Jadhav200 if you cannot read the docs and not watch a literally youtube video on how to set up the extension and cannot give details, dont raise an issue
