### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by khitishkumar18** [31b4/Leetcode-Premium-Bypass#75]
cant find developer mode in my extensions where files are uploaded

**Comment by 31b4** [comment]
what browser? @khitishkumar18

**Comment by khitishkumar18** [comment]
Chrome

**Comment by Gourav-21** [comment]
@khitishkumar18, learn to use Google, but still, go to this link: https://github.com/31b4/Leetcode-Premium-Bypass/issues/44#issue-2088330037.

**Comment by khitishkumar18** [comment]
It works!
