### ISSUE TITLE
Not able to access premium as a whole.

### ISSUE THREAD

**Issue by dinesh-2020-code** [31b4/Leetcode-Premium-Bypass#76]
The issue I'm facing that I'm unable to use all premium feature. Most importantly I wish to access the editorial of the problems available on the leetcode. Editorials for all problems must be available.
For ex: The question code is 629, it's showing editorial is locked.

**Expected behavior**
I wish that Editorials for the problems should be there.

**Screenshots**
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/74357919/1959e860-2661-456f-92d6-0623035de8ef)

 - Browser Chrome

**Comment by 31b4** [comment]
@yeskeakash @dinesh-2020-code  Use split UI, here is how: #14
