### ISSUE TITLE
Premium problemset is locked

### ISSUE THREAD

**Issue by Rupali59** [31b4/Leetcode-Premium-Bypass#77]
**Describe the bug**
Premium problems are still locked

**To Reproduce**
1. Load the plugin successfully (frequency bars are visible).
2. Click on a company (eg Facebook)
3. Select one of the asked questions.
4. The problem list gives "Subscribe to unlock" message.
5. The error is not resolved even with reload.

**Expected behavior**
The premium problem should have been unlocked.

**Screenshots**
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/12728796/fa3b91e5-f108-43fe-ac97-8b95fca46022)

**Desktop (please complete the following information):**
 - Chrome Version 121.0.6167.86 (Official Build) (64-bit)

**Comment by 31b4** [comment]
@Rupali59 Currently accessing premium questions through problem list isnt possible.

Search for them here: https://leetcode.com/problemset/ and then refresh the page

**Comment by shivamgupta28111** [comment]
can I use this extension now also ?

**Comment by 31b4** [comment]
#99
