### ISSUE TITLE
Premium problems are locked. For eg. https://leetcode.com/problems/meeting-rooms-ii/description/

### ISSUE THREAD

**Issue by mugdhakolhe** [31b4/Leetcode-Premium-Bypass#78]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
Please follow the video: https://www.youtube.com/watch?v=tARc8QI5AnE&ab_channel=31b4

**Comment by mugdhakolhe** [comment]
Thanks! it worked. Able to view questions (only submission and testcases are blocked now)

**Comment by 31b4** [comment]
Not yet, we gonna make it work soon.
