### ISSUE TITLE
premium questions are not working.

### ISSUE THREAD

**Issue by tidalu** [31b4/Leetcode-Premium-Bypass#79]
![err](https://github.com/31b4/Leetcode-Premium-Bypass/assets/127156318/846566b3-035a-4ecb-98ff-e8426e351643)

my dynamic layout is off, but i am not able to see premium questions, but it is showing questions company basec on the main problems page,

**Comment by 31b4** [comment]
Please follow the video: https://www.youtube.com/watch?v=tARc8QI5AnE&ab_channel=31b4

**Comment by 31b4** [comment]
skill issue, its working for everyone else, and i cant do anything with an issue like this, lack of description.

**Comment by tidalu** [comment]
it is okay, it is working, for all other senarios but only for premium questions it is not working, i did what u have shown in the video
