### ISSUE TITLE
Manifest file is missing or unreadable 

### ISSUE THREAD

**Issue by pankajkrdev** [31b4/Leetcode-Premium-Bypass#81]
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by tusharsharma136** [comment]
Open the folder. Copy all the files:
![image](https://github.com/31b4/Leetcode-Premium-Bypass/assets/117950077/9396fe4e-cab1-4867-b9e3-6c8765b8772f)

 and paste it in the dist folders. 

Now try to load again. The error resolves.

**Comment by 31b4** [comment]
Here is how to solve it: #44
