### ISSUE TITLE
Not able to view solution in editorial.

### ISSUE THREAD

**Issue by ighitesh** [31b4/Leetcode-Premium-Bypass#82]
**Describe the bug**
I am not able to view the solutions of any problem in editorial section.

**To Reproduce**
1. Go to 'any problem'
2. Click on 'editorial'
3. Scroll down to 'editorial section'

**Expected behavior**
It should allow to view the solutions in the editorial section.

**Screenshots**
Attached the screenshot of the editorial for the leetcode problem number 64.
<img width="1149" alt="Screenshot 2024-01-29 at 9 42 42 PM" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/96572055/706be833-3b14-470d-8b27-6ea30ab872da">

**Desktop (please complete the following information):**
 - Using Chrome on Mac M1

**Additional context**
Nothing else.

**Comment by raj-chinagundi** [comment]
They updated the dynamic ui layout, we cant revert to split view anymore, hence not view editorials

**Comment by ighitesh** [comment]
Okayyy, got it. Thanks for the reply. When switching back to Split View
mode, it’s working. Thanks :))

**Comment by 31b4** [comment]
> They updated the dynamic ui layout, we cant revert to split view anymore, hence not view editorials

@raj-chinagundi we can, what do you mean?

**Comment by ighitesh** [comment]
Yaa in settings, we can revert back to Split View layout. Making the
editorial one working.

**Comment by raj-chinagundi** [comment]
@31b4 see this the run button used to be on top its on bottom right now I cant see setting either
<img width="1430" alt="Screenshot 2024-02-03 at 5 16 11 PM" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75333151/d93b523b-7434-40d1-8c5c-977c72dd9ca9">

**Comment by ighitesh** [comment]
See on the top right, I have setting option
<img width="1432" alt="Screenshot 2024-02-03 at 5 23 39 PM" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/96572055/e68a5685-cc76-47a9-90c5-363842f2317e">
Don't know, why leetcode showing different outputs.
