### ISSUE TITLE
Cannot open premium question

### ISSUE THREAD

**Issue by anirudhmura** [31b4/Leetcode-Premium-Bypass#84]
**Describe the bug**
I followed all the steps on the video but I still cannot access the editor. I can see the questions but doesnot allow me to go into the editor. you can see in the image below.
![bug](https://github.com/31b4/Leetcode-Premium-Bypass/assets/137559437/a9e28f09-af04-41c3-b275-031972066e00)
![bug](https://github.com/31b4/Leetcode-Premium-Bypass/assets/137559437/46b41468-93ae-4f36-8908-a19c47a00dbf)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
Editorial is currently not available in editorial, we are working on fixing that
