### ISSUE TITLE
Manifest file missing or Unreadable Issue

### ISSUE THREAD

**Issue by itzmysteryy** [31b4/Leetcode-Premium-Bypass#85]
When I try to load the extension it replies back Manifest file missing or unreadable. Could not load manifest.
![Screenshot 2024-01-30 102806](https://github.com/31b4/Leetcode-Premium-Bypass/assets/150412347/4f22a6d8-8edd-4bdb-9dfa-7014123ae397)

**Comment by 31b4** [comment]
Here is how to solve it: #44

**Comment by itzmysteryy** [comment]
Tysm 🙏🙏
