### ISSUE TITLE
Not able to open SQL premium section 

### ISSUE THREAD

**Issue by Lancelot88** [31b4/Leetcode-Premium-Bypass#86]
![Screenshot (125)](https://github.com/31b4/Leetcode-Premium-Bypass/assets/89684491/48fa75b3-8ee9-4aff-985a-775a0da12abe)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 31b4** [comment]
Correct, the extension currently cannot unlock these premium sections, we are working on fixing them too.

**Comment by Lancelot88** [comment]
okay thanks
