### ISSUE TITLE
Request to  add the view dislike in dynamic ui. 

### ISSUE THREAD

**Issue by godwin-jg** [31b4/Leetcode-Premium-Bypass#89]
Can you add the view dislike feature its currently missing out in dynamic ui. would be great to have it in here.

i think this is the greatest extension currently out there for leetcode :)

**Comment by godwin-jg** [comment]
yes exactly. if you revert it back to old version from the menu you can actually see the dislikes. 
like this :
![leetcode-old-likeui](https://github.com/31b4/Leetcode-Premium-Bypass/assets/89068702/ed894a4e-41a9-4cbf-ad8a-89aaf33ccb91)

i dont know for some reasons they decided to remove it from the new layout. Leetcode has a lot of great problems but sometimes some problems can be crazy. So i think the to  have that dislike option back would be great(imho).

**Comment by 31b4** [comment]
Yeah it was removed like from youtube. 

And since I have received a takedown from leetcode, i had to shut it down, so im not working on this extension anymore.

**Comment by godwin-jg** [comment]
Anyway Great props to you, still awesome.
