### ISSUE TITLE
Bug , with new question adding in leetcode from contest As Hint tag is get green in place of companies

### ISSUE THREAD

**Issue by PrakarshSingh5** [31b4/Leetcode-Premium-Bypass#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by PrakarshSingh5** [comment]
![Screenshot 2024-02-05 115127](https://github.com/31b4/Leetcode-Premium-Bypass/assets/108565574/f5945d68-a92f-4db9-8034-9c6d9edc1301)

**Comment by 31b4** [comment]
Refresh
